### ISSUE TITLE
Use /tmp as default temp dir

### ISSUE THREAD

**Issue by voidus** [mkrakowitzer/puppet-deploy#11]
Hey, is there any reason why you're not using /tmp as the default temp dir?

**Comment by mkrakowitzer** [comment]
seem reasonable, ill change it. In my environment /tmp is probably to small but it should work for most people.

**Comment by voidus** [comment]
Please make sure that you don't change /tmp's permissions. It's supposed to be 1777, I think puppet-deploy sets the temp dir to 755 or something.

**Comment by mkrakowitzer** [comment]
I dont think it does :/ We set the temp directory like this. Which should not be /tmp anyway.

  file { $tempdir:
    ensure => directory,
  }

**Comment by mkrakowitzer** [comment]
I cant reproduce this, if you could provide more info that would be appreciated.
