### ISSUE TITLE
Cannot pass undef as value in class in puppet 2.7

### ISSUE THREAD

**Issue by preflightsiren** [mkrakowitzer/puppet-deploy#12]
error:

``` shell
Must pass command_options to
Deploy::Untar[/tmp/deploy/atlassian-stash-2.10.1.tar.gz] at
/tmp/vagrant-puppet-2/modules-1/deploy/manifests/untar.pp:45 on node stash1
```

https://projects.puppetlabs.com/issues/16221

I'm thinking about setting undef as the default value of command_options in deploy::untar

**Comment by preflightsiren** [comment]
pull request -> https://github.com/mkrakowitzer/puppet-deploy/pull/13

**Comment by mkrakowitzer** [comment]
Thanks. Merged.
