### ISSUE TITLE
Is it possible for you to register it on forge.puppetlabs.com?

### ISSUE THREAD

**Issue by actionjack** [mkrakowitzer/puppet-deploy#2]
Hi there I've just started to use your module and I was wondering if it's possible for you to register it on forge.puppetlabs.com so it's easier to include it in librarian-puppet and for others to find it?

**Comment by mkrakowitzer** [comment]
Sure, ill take care of it.

**Comment by mkrakowitzer** [comment]
OK, I have registered it on puppet forge

puppet module install mkrakowitzer/deploy --version 0.0.1

**Comment by actionjack** [comment]
Thank you sir!
